name: "build"

on:
  pull_request:
    paths-ignore:
      - ".docs/**"
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        latte: [ '', '--prefer-lowest' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, iconv, json, mbstring, tokenizer
          coverage: none
      - run: composer install --no-interaction
      - run: composer update latte/latte ${{ matrix.latte }} --no-interaction
      - run: make tests

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: curl, iconv, json, mbstring, tokenizer
          coverage: pcov
      - run: composer install --no-interaction
      - run: make coverage-clover
      - uses: codecov/codecov-action@v1

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
      - run: composer install --no-interaction
      - run: make phpstan

  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
      - run: composer install --no-interaction
      - run: make cs
